/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AreaFiltros: typeof import('./src/components/Estoque/AreaFiltros.vue')['default']
    AreaTabela: typeof import('./src/components/Estoque/AreaTabela.vue')['default']
    CriarProduto: typeof import('./src/components/Estoque/CriarProduto.vue')['default']
    EstoquePage: typeof import('./src/components/Pages/EstoquePage.vue')['default']
    HeaderEstoque: typeof import('./src/components/Estoque/HeaderEstoque.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IndexPage: typeof import('./src/components/Pages/indexPage.vue')['default']
    LinhaProduto: typeof import('./src/components/Utils/LinhaProduto.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelecaoModulo: typeof import('./src/components/Utils/SelecaoModulo.vue')['default']
    VogalPage: typeof import('./src/components/Pages/VogalPage.vue')['default']
  }
}
